FROM centos:7
RUN sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-* && \ 
    sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*

RUN yum install -y epel-release\
    python3 python3-pip

WORKDIR /app

COPY requirements.txt .
COPY cars.py .

RUN pip3 install --no-cache-dir -r requirements.txt

EXPOSE 8082

CMD ["python3", "cars.py"]
